language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
script:
  - ./gradlew build